# Copyright (C) 2016-Present Pivotal Software, Inc. All rights reserved.
# This program and the accompanying materials are made available under the terms of the under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

---
broker:
  port: 8080
  username: username
  password: password
bosh:
  url: some-url
  authentication:
    basic:
      username: some-username
      password: some-password
cf:
  url: some-cf-url
  root_ca_cert: some-cf-cert
  uaa:
    url: a-uaa-url
    authentication:
      user_credentials:
        username: some-cf-username
        password: some-cf-password
service_adapter:
service_deployment:
  releases:
    - name: some-name
      version: some-version
      jobs: [some-job]
  stemcell:
    os: ubuntu-trusty
    version: 1234
service_catalog:
  id: some-id
  service_name: some-marketplace-name
  service_description: some-description
  bindable: true
  plan_updatable: true
  metadata:
    display_name: some-service-display-name
  tags:
    - some-tag
    - some-other-tag
  plans:
    - name: some-dedicated-name
      plan_id: some-dedicated-plan-id
      description: I'm a dedicated plan
      metadata:
        display_name: Dedicated-Cluster
        bullets:
          - bullet one
          - bullet two
          - bullet three
      quotas:
        service_instance_limit: 1
      properties:
        persistence: true
      instance_groups:
        - name: redis-server
          vm_type: some-vm
          persistent_disk_type: some-disk
          instances: 34
          networks: [ net1, net2 ]
        - name: redis-server-2
          vm_type: some-vm-2
          instances: 3
          networks: [ net4, net5 ]
